name: redux_persist_flutter
description: Redux Persist Flutter Integration
version: 0.4.0
homepage: https://github.com/Cretezy/redux_persist/tree/master/packages/redux_persist_flutter
author: Charles Crete <charles@cretezy.com>

environment:
  sdk: ">=1.24.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^0.3.1
  shared_preferences: ^0.4.0
  redux_persist: ^0.4.0

dev_dependencies:
  # for example
  redux: ^2.1.1
  flutter_redux: ^0.3.5
  redux_persist:
    path: ../redux_persist

dependency_overrides:
  redux_persist:
    path: ../redux_persist
