name: redux_persist_flutter
description: Redux Persist Flutter Integration with custom storage engines
version: 0.8.1
homepage: https://github.com/Cretezy/redux_persist/tree/master/packages/redux_persist_flutter
author: Charles Crete <charles@cretezy.com>

environment:
  sdk: ">=2.0.0-dev <3.0.0"

dependencies:
  flutter:
    sdk: "flutter"
  path_provider: "^1.1.2"
  shared_preferences: "^0.5.1+1"
  redux_persist: "^0.8.0"

# Used for development
#dependency_overrides:
#  redux_persist:
#    path: ../redux_persist
