name: redux_persist_web
description: Redux Persist Web Integration
version: 0.8.0-rc.0
homepage: https://github.com/Cretezy/redux_persist/tree/master/packages/redux_persist_web
author: Charles Crete <charles@cretezy.com>

environment:
  sdk: ">=1.24.0 <3.0.0"

dependencies:
  redux_persist: "^0.8.0-rc.0"

# Used for development
#dependency_overrides:
#  redux_persist:
#    path: ../redux_persist
