name: redux_persist
description: Persist Redux State
version: 0.7.0-rc.2
homepage: https://github.com/Cretezy/redux_persist/tree/master/packages/redux_persist
author: Charles Crete <charles@cretezy.com>

environment:
  sdk: ">=2.0.0-dev <2.0.0"

dependencies:
  redux: "^3.0.0"

dev_dependencies:
  test: "^0.12.33"
