name: redux_persist
description: Persist Redux State
version: 0.5.2
homepage: https://github.com/Cretezy/redux_persist/tree/master/packages/redux_persist
author: Charles Crete <charles@cretezy.com>

environment:
  sdk: ">=1.24.0 <2.0.0"

dependencies:
  redux: ^2.1.1

dev_dependencies:
  test: "^0.12.32+1"
